failed: [192.168.41.33] (item={'value': {u'environment': {u'DUMMY_ENVIRONMENT': u'kolla_useless_env'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-cron:ocata',
 u'volumes': [u'/etc/kolla//cron/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', 
u'kolla_logs:/var/log/kolla/'], u'container_name': u'cron'}, 'key': u'cron'}) => {"changed": true, "item": {"key": "cron", "value": {"container_name": "cron", 
"environment": {"DUMMY_ENVIRONMENT": "kolla_useless_env"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-cron:ocata", 
"volumes": ["/etc/kolla//cron/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  
File \"/tmp/ansible_YeXUBk/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_YeXUBk/ansible_module_kolla_docker.py\",
line 218, in __init__\\n   
 self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    
config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}


failed: [192.168.41.32] (item={'value': {u'environment': {u'DUMMY_ENVIRONMENT': u'kolla_useless_env'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-cron:ocata', u'volumes': [u'/etc/kolla//cron/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'kolla_logs:/var/log/kolla/'], u'container_name': u'cron'}, 'key': u'cron'}) => {"changed": true, "item": {"key": "cron", "value": {"container_name": "cron", "environment": {"DUMMY_ENVIRONMENT": "kolla_useless_env"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-cron:ocata", "volumes": ["/etc/kolla//cron/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_D2f64X/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_D2f64X/ansible_module_kolla_docker.py\", line 218, in __init__\\n    self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}


failed: [192.168.41.31] (item={'value': {u'environment': {u'DUMMY_ENVIRONMENT': u'kolla_useless_env'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-cron:ocata', u'volumes': [u'/etc/kolla//cron/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'kolla_logs:/var/log/kolla/'], u'container_name': u'cron'}, 'key': u'cron'}) => {"changed": true, "item": {"key": "cron", "value": {"container_name": "cron", "environment": {"DUMMY_ENVIRONMENT": "kolla_useless_env"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-cron:ocata", "volumes": ["/etc/kolla//cron/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_v1jftK/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_v1jftK/ansible_module_kolla_docker.py\", line 218, in __init__\\n    self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}


failed: [192.168.41.33] (item={'value': {u'environment': {u'http_proxy': u'http://172.30.212.32:8080', u'KOLLA_CONFIG_STRATEGY': u'COPY_ALWAYS'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-fluentd:pike', u'volumes': [u'/etc/kolla//fluentd/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'kolla_logs:/var/log/kolla/'], u'container_name': u'fluentd'}, 'key': u'fluentd'}) => {"changed": true, "item": {"key": "fluentd", "value": {"container_name": "fluentd", "environment": {"KOLLA_CONFIG_STRATEGY": "COPY_ALWAYS", "http_proxy": "http://172.30.212.32:8080"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-fluentd:pike", "volumes": ["/etc/kolla//fluentd/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_CbU8Co/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_CbU8Co/ansible_module_kolla_docker.py\", line 218, in __init__\\n    self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}


failed: [192.168.41.31] (item={'value': {u'environment': {u'http_proxy': u'http://172.30.212.32:8080', u'KOLLA_CONFIG_STRATEGY': u'COPY_ALWAYS'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-fluentd:pike', u'volumes': [u'/etc/kolla//fluentd/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'kolla_logs:/var/log/kolla/'], u'container_name': u'fluentd'}, 'key': u'fluentd'}) => {"changed": true, "item": {"key": "fluentd", "value": {"container_name": "fluentd", "environment": {"KOLLA_CONFIG_STRATEGY": "COPY_ALWAYS", "http_proxy": "http://172.30.212.32:8080"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-fluentd:pike", "volumes": ["/etc/kolla//fluentd/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_we76WI/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_we76WI/ansible_module_kolla_docker.py\", line 218, in __init__\\n    self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}


failed: [192.168.41.32] (item={'value': {u'environment': {u'http_proxy': u'http://172.30.212.32:8080', u'KOLLA_CONFIG_STRATEGY': u'COPY_ALWAYS'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-fluentd:pike', u'volumes': [u'/etc/kolla//fluentd/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'kolla_logs:/var/log/kolla/'], u'container_name': u'fluentd'}, 'key': u'fluentd'}) => {"changed": true, "item": {"key": "fluentd", "value": {"container_name": "fluentd", "environment": {"KOLLA_CONFIG_STRATEGY": "COPY_ALWAYS", "http_proxy": "http://172.30.212.32:8080"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-fluentd:pike", "volumes": ["/etc/kolla//fluentd/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_E1kUeg/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_E1kUeg/ansible_module_kolla_docker.py\", line 218, in __init__\\n    self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}


failed: [192.168.41.33] (item={'value': {u'environment': {u'ANSIBLE_LIBRARY': u'/usr/share/ansible', u'ANSIBLE_NOCOLOR': u'1'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-kolla-toolbox:ocata', u'privileged': True, u'volumes': [u'/etc/kolla//kolla-toolbox/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'/dev/:/dev/', u'/run/:/run/:shared', u'kolla_logs:/var/log/kolla/'], u'container_name': u'kolla_toolbox'}, 'key': u'kolla-toolbox'}) => {"changed": true, "item": {"key": "kolla-toolbox", "value": {"container_name": "kolla_toolbox", "environment": {"ANSIBLE_LIBRARY": "/usr/share/ansible", "ANSIBLE_NOCOLOR": "1"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-kolla-toolbox:ocata", "privileged": true, "volumes": ["/etc/kolla//kolla-toolbox/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "/dev/:/dev/", "/run/:/run/:shared", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_OvsN2J/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_OvsN2J/ansible_module_kolla_docker.py\", line 218, in __init__\\n    self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}


failed: [192.168.41.32] (item={'value': {u'environment': {u'ANSIBLE_LIBRARY': u'/usr/share/ansible', u'ANSIBLE_NOCOLOR': u'1'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-kolla-toolbox:ocata', u'privileged': True, u'volumes': [u'/etc/kolla//kolla-toolbox/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'/dev/:/dev/', u'/run/:/run/:shared', u'kolla_logs:/var/log/kolla/'], u'container_name': u'kolla_toolbox'}, 'key': u'kolla-toolbox'}) => {"changed": true, "item": {"key": "kolla-toolbox", "value": {"container_name": "kolla_toolbox", "environment": {"ANSIBLE_LIBRARY": "/usr/share/ansible", "ANSIBLE_NOCOLOR": "1"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-kolla-toolbox:ocata", "privileged": true, "volumes": ["/etc/kolla//kolla-toolbox/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "/dev/:/dev/", "/run/:/run/:shared", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_M2I3zm/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_M2I3zm/ansible_module_kolla_docker.py\", line 218, in __init__\\n    self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}


failed: [192.168.41.31] (item={'value': {u'environment': {u'ANSIBLE_LIBRARY': u'/usr/share/ansible', u'ANSIBLE_NOCOLOR': u'1'}, u'image': u'ecr.ebaykorea.com/kolla/centos-binary-kolla-toolbox:ocata', u'privileged': True, u'volumes': [u'/etc/kolla//kolla-toolbox/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'/dev/:/dev/', u'/run/:/run/:shared', u'kolla_logs:/var/log/kolla/'], u'container_name': u'kolla_toolbox'}, 'key': u'kolla-toolbox'}) => {"changed": true, "item": {"key": "kolla-toolbox", "value": {"container_name": "kolla_toolbox", "environment": {"ANSIBLE_LIBRARY": "/usr/share/ansible", "ANSIBLE_NOCOLOR": "1"}, "image": "ecr.ebaykorea.com/kolla/centos-binary-kolla-toolbox:ocata", "privileged": true, "volumes": ["/etc/kolla//kolla-toolbox/:/var/lib/kolla/config_files/:ro", "/etc/localtime:/etc/localtime:ro", "/dev/:/dev/", "/run/:/run/:shared", "kolla_logs:/var/log/kolla/"]}}, "msg": "'Traceback (most recent call last):\\n  File \"/tmp/ansible_dCfdaz/ansible_module_kolla_docker.py\", line 795, in main\\n    dw = DockerWorker(module)\\n  File \"/tmp/ansible_dCfdaz/ansible_module_kolla_docker.py\", line 218, in __init__\\n    self.dc = get_docker_client()(**options)\\n  File \"/usr/lib/python2.7/site-packages/docker/api/client.py\", line 128, in __init__\\n    config_dict=self._general_configs, credstore_env=credstore_env,\\nTypeError: load_config() got an unexpected keyword argument \\'config_dict\\'\\n'"}
